export const tagOptions = [
    { value: "beige", label: "Beige"},
    { value: "black", label: "Black"},
    { value: "blue", label: "Blue" },
    { value: "bright", label: "Bright" },
    { value: "brown", label: "Brown" },
    { value: "calm", label: "Calm" },
    { value: "caramel", label: "Caramel" },
    { value: "coffee", label: "Coffee" },
    { value: "cream", label: "Cream" },
    { value: "dark", label: "Dark" },
    { value: "gray", label: "Gray" },
    { value: "green", label: "Green" },
    { value: "halloween", label: "Halloween" },
    { value: "kids", label: "Kids" },
    { value: "light", label: "Light" },
    { value: "maroon", label: "Maroon" },
    { value: "monochromatic", label: "Monochromatic" },
    { value: "neutral", label: "Neutral" },
    { value: "olive", label: "Olive" },
    { value: "orange", label: "Orange" },
    { value: "peach", label: "Peach" },
    { value: "pink", label: "Pink" },
    { value: "purple", label: "Purple" },
    { value: "red", label: "red" },
    { value: "sunny", label: "Sunny" },
    { value: "tan", label: "Tan" },
    { value: "teal", label: "Teal" },
    { value: "water", label: "Water" },
    { value: "white", label: "White" },
    { value: "yellow", label: "Yellow" }

  ]
  