export { default as Welcome } from './Welcome'
export { default as Home } from './Home'
export { default as Dashboard } from './Dashboard'
export { default as Signup } from './Signup'
export { default as Nav } from './Nav'